### ISSUE TITLE
Documentation link in README returns 403 Forbidden

### ISSUE THREAD

**Issue by otherjoel** [97jaz/gregor#10]
The link to `http://pkg-build.racket-lang.org/doc/gregor/index.html` in README.md is broken.

Also, searches for library functions like `~t` and `now/moment` on Racket’s docs site return no results.

**Comment by 97jaz** [comment]
Yeah, there was an announcement on the dev list a couple/few weeks ago that we could start using arbitrary strings for documentation categories (instead of the ones listed here [http://docs.racket-lang.org/raco/setup-info.html?q=scribblings#%28idx._%28gentag._4._%28lib._scribblings%2Fraco%2Fraco..scrbl%29%29%29]). However, it turns out that this won't work for versions < 6.4 (which isn't even out yet). So, I'll revert that change. Thanks for the report.

**Comment by 97jaz** [comment]
@otherjoel: the documentation links are working now. Thanks again.
