### ISSUE TITLE
parse-date returns the wrong date

### ISSUE THREAD

**Issue by mfelleisen** [97jaz/gregor#34]
This looks wrong to me: 
```
> (parse-date "27.03.2020" "d.m.y")
#<date 2020-01-27>
```

**Comment by 97jaz** [comment]
Hi Matthias, the pattern for months uses uppercase ‘M’s. Your example is using a minute pattern. What’s happening (though this is admittedly confusing) is that it’s parsing successfully parsing 3 minutes, but since you asked for a date (rather than a datetime), that doesn’t appear in the result. But the default value for the month (1) appears, since the pattern isn’t asking for a
month.

**Comment by mfelleisen** [comment]
I thought I had copied this from the docs but I double-checked and I am wrong. Sorry for the bother, I'll close it.
